version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1
  python: circleci/python@0.2.1


jobs:
  build:
    executor: python/default
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - heroku/install
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: "Creating DB config"
          command: "sh create_db.sh"
      - run:
          name: "Running unit tests"
          command: "python -m unittest test/*.py -v"

  deploy:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - heroku/install
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: "Creating DB config"
          command: "sh create_db.sh"
      - run:
          name: "Running unit tests"
          command: "python -m unittest test/*.py -v"
      - run:
          name: "Deploying to Amazon EC2 Instance"
          command: "sh deploy.sh"

workflows:
  heroku_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master