version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - heroku/install
      - run:
          name: Installing requirements
          command: "pip install -r requirements.txt"
      - run:
          name: "Running unit tests"
          command: "python -m unittest test/*.py -v"

  deploy:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - heroku/install
      - run:
          name: Installing requirements
          command: "pip install -r requirements.txt"
      - run:
          name: "Running unit tests"
          command: "python -m unittest test/*.py -v"
      - run:
          name: "Creating DB config"
          command: "sh create_db.sh"
      - heroku/deploy-via-git

workflows:
  heroku_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master