version: 2.1

orbs:
  python: circleci/python@0.2.1


jobs:
  build:
    executor: python/default
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: "Creating DB config"
          command: "sh create_db.sh"
      - run:
          name: "Running unit tests"
          command: "python -m unittest src/test/*.py -v"

  deploy:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: "Creating DB config"
          command: "sh create_db.sh"
      - run:
          name: "Running unit tests"
          command: "python -m unittest src/test/*.py -v"
      - add_ssh_keys:
          fingerprints:
            - "3a:6f:31:6d:f5:bc:f2:fb:d7:b8:11:21:aa:e8:b9:65"
      - run:
          name: "Deploying to Amazon EC2 Instance"
          command: "sh deploy.sh"

workflows:
  heroku_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master